// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskForLightpoint.Data;

namespace TaskForLightpoint.Migrations
{
    [DbContext(typeof(TaskForLightpointContext))]
    [Migration("20191128154853_additionalrowinserted")]
    partial class additionalrowinserted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskForLightpoint.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TaskForLightpoint.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Shop");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ad2c4e5-be99-410e-97ad-8df454251db4"),
                            Adress = "Test 1.1",
                            Name = "Test 1.0",
                            OpeningHours = "Test1.2"
                        },
                        new
                        {
                            Id = new Guid("7d0423f9-3d0e-4d83-9d4f-2ff485391081"),
                            Adress = "Test 2.1",
                            Name = "Test 2.0",
                            OpeningHours = "Test2.2"
                        });
                });

            modelBuilder.Entity("TaskForLightpoint.Models.ShopProduct", b =>
                {
                    b.Property<Guid>("ShopFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShopFK", "ProductFK");

                    b.HasAlternateKey("Id");

                    b.HasIndex("ProductFK");

                    b.ToTable("ShopProduct");
                });

            modelBuilder.Entity("TaskForLightpoint.Models.ShopProduct", b =>
                {
                    b.HasOne("TaskForLightpoint.Models.Product", "Product")
                        .WithMany("ShopProducts")
                        .HasForeignKey("ProductFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskForLightpoint.Models.Shop", "Shop")
                        .WithMany("ShopProducts")
                        .HasForeignKey("ShopFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
