// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskForLightpoint.Data;

namespace TaskForLightpoint.Migrations
{
    [DbContext(typeof(TaskForLightpointContext))]
    [Migration("20191128155456_additionalrowinserted2")]
    partial class additionalrowinserted2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskForLightpoint.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07ce772c-0e21-4ec4-b24a-d642a826e6d2"),
                            Description = "Test 1.1",
                            Name = "Test 1.0"
                        },
                        new
                        {
                            Id = new Guid("69bc623b-1fa5-47ca-a160-4170fc3a935a"),
                            Description = "Test 2.1",
                            Name = "Test 2.0"
                        });
                });

            modelBuilder.Entity("TaskForLightpoint.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Shop");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a03bd72-47b9-4996-822e-3fbea418c4a5"),
                            Adress = "Test 1.1",
                            Name = "Test 1.0",
                            OpeningHours = "Test1.2"
                        },
                        new
                        {
                            Id = new Guid("2b546b53-bb16-4279-9892-5ecdd7075597"),
                            Adress = "Test 2.1",
                            Name = "Test 2.0",
                            OpeningHours = "Test2.2"
                        });
                });

            modelBuilder.Entity("TaskForLightpoint.Models.ShopProduct", b =>
                {
                    b.Property<Guid>("ShopFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShopFK", "ProductFK");

                    b.HasAlternateKey("Id");

                    b.HasIndex("ProductFK");

                    b.ToTable("ShopProduct");
                });

            modelBuilder.Entity("TaskForLightpoint.Models.ShopProduct", b =>
                {
                    b.HasOne("TaskForLightpoint.Models.Product", "Product")
                        .WithMany("ShopProducts")
                        .HasForeignKey("ProductFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskForLightpoint.Models.Shop", "Shop")
                        .WithMany("ShopProducts")
                        .HasForeignKey("ShopFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
